/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.tp.entity.reservation;

import lombok.*;
import jakarta.persistence.*;

import java.util.ArrayList;
import java.util.List;


@Getter
@Setter
@NoArgsConstructor
@RequiredArgsConstructor
@AllArgsConstructor
@Entity(name = "Client")
@Table(
        name = "client",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "client_email_unique",
                        columnNames = "client_email"
                )
        }

)
public class Client {
    @Id
//    @SequenceGenerator(
//            name = "sequence_client",
//            sequenceName = "sequence_client",
//            allocationSize = 1
//    )
//    @GeneratedValue(
//            strategy = GenerationType.SEQUENCE,
//            generator = "sequence_client"
//    )
    @Column(
            name = "client_id",
            nullable = false
    )
    private Long id;

    @Column(
            name = "client_first_name",
            nullable = false
    )
    @NonNull
    private String first_name;

    @Column(
            name = "client_last_name",
            nullable = false
    )
    @NonNull
    private String last_name;

    @Column(
            name = "client_adresse",
            nullable = false,
            length = 25
    )
    @NonNull
    private String address;

    @Column(
            name = "client_telephone",
            nullable = false,
            length = 13
    )
    @NonNull
    private String telephone;

    @Column(
            name = "client_email",
            nullable = false
    )
    @NonNull
    private String email;

    //ERD party
    @OneToMany(
            mappedBy = "client"
    )
    private List<Reservation> list_reservation = new ArrayList<>();

    public void reserver(Reservation reservation){
        reservation.setClient(this);
            list_reservation.add(reservation);
    }

}

