/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.tp.entity.reservation;

import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.Collection;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity(name = "Passager")
@Table(name = "passager")
public class Passager{

    /*
     * ID Vole Sequence Generator (passager_sequence) with Strategy SEQUENCE
     * Column name is : passager_id
     * */

    @Id
    @SequenceGenerator(
            name = "passager_sequence",
            sequenceName = "passager_sequence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "passager_sequence"
    )
    @Column(
            name = "passager_id"
            ,nullable = false
    )
    private Long passagerID;

    /*
     * Passager first name type String
     * Column name is : passager_first_name
     * */

    @Column(
            name = "passager_first_name"
            ,nullable = false
    )
    private String first_name;

    /*
     * Passager last name type String
     * Column name is : passager_last_name
     * */

    @Column(
            name = "passager_last_name"
            ,nullable = false
    )
    private String last_name;

    /*
    * Mapping Table
    * */
    @OneToMany(
            mappedBy = "passager",
            cascade = {CascadeType.ALL}
    )
    private Collection<Reservation> reservations = new ArrayList<>();

    public Passager(String first_name, String last_name) {
        this.first_name = first_name;
        this.last_name = last_name;
    }
}