/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.tp.entity.reservation;

import com.tp.entity.reservation.Reservation;
import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

@Getter
@Setter
@NoArgsConstructor
@RequiredArgsConstructor
@Entity
@Table
public class Passager {

    @Id
    @SequenceGenerator(
            name = "passagersquence",
            sequenceName = "passagersquence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "passagersquence"
    )
    @Column(
            name = "passager_id",
            nullable = false

    )
    private Long id;

    @Column(
            name = "passager_first_name",
            nullable = false
    )
    @NonNull
    private String first_name;

    @Column(
            name = "passager_last_name",
            nullable = false
    )
    @NonNull
    private String last_name;

//    ERD party
    @OneToMany(
            mappedBy = "passager",
            fetch = FetchType.LAZY,
            orphanRemoval = true,
            cascade = CascadeType.ALL
    )
    private Collection<Reservation> reservations = new ArrayList<>() ;

}