/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.tp.entity.reservation;

import jakarta.persistence.*;
import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@RequiredArgsConstructor
@ToString
@Entity(name = "Passager")
@Table(name = "passager")
public class Passager{

    @Id
    @SequenceGenerator(
            name = "passager_sequence",
            sequenceName = "client_sequence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "passager_sequence"
    )
    @Column(
            name = "passager_id",
            nullable = false
    )
    private Long id;

    @Column(
            name = "passager_first_name",
            nullable = false
    )
    @NonNull
    private String first_name;

    @Column(
            name = "passager_last_name",
            nullable = false
    )
    @NonNull
    private String last_name;
}