/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.tp.entity.vole;

import lombok.*;

import jakarta.persistence.*;
import java.util.Collection;

@Getter
@Setter
@NoArgsConstructor @AllArgsConstructor
@Table(name = "compagniesaerienne")
@Entity(name = "Compagniesaerienne")
@ToString
public class CompagniesAerienne {

    @Id
    @SequenceGenerator(
            name = "compagnie_sequence",
            sequenceName = "compagnie_sequence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "compagnie_sequence"
    )
    @Column(
            name = "compagnie_id",
            nullable = false
    )
    private Long id;

    @Column(
            name = "compagnie_name",
            nullable = false,
            length = 25
    )
    private String name;

    //ER Party
    @OneToMany(
            cascade = {CascadeType.PERSIST,CascadeType.REMOVE},
            mappedBy = "compagniesAerienne",
            fetch = FetchType.LAZY,
            orphanRemoval = true)
    private Collection<Vole> vole;

    //à triter
    @OneToOne(
            cascade = {CascadeType.PERSIST,CascadeType.REMOVE},
            mappedBy = "compagniesAerienne",
            fetch = FetchType.EAGER,
            orphanRemoval = true)
    private VoleGenirique voleCompanie = new VoleGenirique();

}