/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.tp.entity.vole;

import lombok.*;

import jakarta.persistence.*;
import java.time.LocalDateTime;


@Getter
@Setter
@NoArgsConstructor @AllArgsConstructor
@Table(name = "info_escale")
@Entity(name = "Info_escale")
@ToString
public class InfoEscale {

    @Id
//    @SequenceGenerator(
//            name = "info_escale_sequence",
//            sequenceName = "info_escale_sequence",
//            allocationSize = 1
//    )
//    @GeneratedValue(
//            strategy = GenerationType.SEQUENCE,
//            generator = "info_escale_sequence"
//    )
    @Column(
            name = "escale_id",
            nullable = false
    )
    private Long id;

    @Column(
            name = "heur_arrive",
            nullable = false
    )
    private LocalDateTime arriver;

    @Column(
            name = "heur_depart",
            nullable = false
    )
    private LocalDateTime depart;

    @Transient
    @Column(
            name = "intervale",
            nullable = false
    )
    private int intervale;

    //ER party
    @ManyToOne
    @JoinColumn(
            name = "aeroport_id",
            referencedColumnName = "aeroport_id",
            foreignKey = @ForeignKey(
                    name = "id",
                    foreignKeyDefinition = "aeroport_id_fk"
            )
    )
private Aeroport aeroport_escale;
    @ManyToOne
    @JoinColumn(
            name = "vole_genirique_id",
            referencedColumnName = "vole_genirique_id",
            foreignKey = @ForeignKey(
                    name = "id",
                    foreignKeyDefinition = "vole-genirique_id_fk"
            )
    )
private VoleGenirique vole_escale;

}