/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.tp.entity.vole;

import com.tp.entity.reservation.Reservation;
import jakarta.transaction.Transactional;
import lombok.*;

import jakarta.persistence.*;
import java.sql.Time;
import java.time.LocalDateTime;
import java.util.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@RequiredArgsConstructor
@Table(name = "vole")
@Entity(name = "Vole")
@ToString
public class Vole {

    @Id
    @SequenceGenerator(
            name = "vole_sequence",
            sequenceName = "vole_sequence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "vole_sequence"
    )
    @Column(
            name = "vole_id",
            nullable = false
    )
    private Long id;

    @Column(
            name = "vole_date_depart",
            nullable = false,
            columnDefinition = "TIMESTAMP WITHOUT TIME ZONE"
    )
    @NonNull
    private LocalDateTime date_departure;

    @Column(
            name = "vole_date_arrive",
            nullable = false,
            columnDefinition = "TIMESTAMP WITHOUT TIME ZONE"
    )
    @NonNull
    private LocalDateTime  date_arrive;

    @Column(
            name = "vole_interval",
            nullable = false
    )

    private Time interval;

    //ER Party
    @OneToMany(
            mappedBy = "vole",
            fetch = FetchType.LAZY,
            orphanRemoval = true,
            cascade = CascadeType.PERSIST
    )
    private Collection<Reservation> reservations = new ArrayList<>();
    @ManyToOne
    private VoleGenirique voleGenirique;
    @ManyToOne
    private CompagniesAerienne compagniesAerienne;

    public void Reserver(Reservation reservation){
        if(!reservations.contains(reservation)){
            reservations.add(reservation);
            reservation.setVole(this);
        }
    }
}