/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.tp.entity.vole;

import com.tp.entity.reservation.Reservation;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collection;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "vole")
@Entity(name = "Vole")
@ToString
public class Vole {

    /*
    * ID Vole Sequence Generator (vole_sequence) with Strategy SEQUENCE
    * Column name is : vole_id
    * */

    @Id
    @SequenceGenerator(
            name = "vole_sequence",
            sequenceName = "vole_sequence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "vole_sequence"
    )
    @Column(
            name = "vole_id"
//            nullable = false
    )
    private Long voleID;

    /*
     * Date of Starting Vole.
     * Type : LocaleDateTime
     * Column : vole_date_depart, Def (TIMESTAMP WITHOUT TIME ZONE) and nonnull
     * */

    @Column(
            name = "vole_date_depart",
//            nullable = false,
            columnDefinition = "TIMESTAMP WITHOUT TIME ZONE"
    )
    private LocalDateTime date_departure;

    /*
     * Date of Ending Vole.
     * Type : LocaleDateTime
     * Column : vole_date_arrive, Def (TIMESTAMP WITHOUT TIME ZONE) and nonnull
     * */

    @Column(
            name = "vole_date_arrive",
//            nullable = false,
            columnDefinition = "TIMESTAMP WITHOUT TIME ZONE"
    )
    private LocalDateTime  date_arrive;

    /*
     * Date of Margin between starting date of vole end ending.
     * Type : LocaleDateTime
     * Column : vole_interval
     * */

    @Column(
            name = "vole_interval"
    )
    private LocalDateTime interval;


    /*
    * Mapping RelationShip with Table : reservations, voleGenirique and compagniesAerienne
    *
    * */

    @OneToMany(
            mappedBy = "vole",
            cascade = {CascadeType.ALL}
    )
    private Collection<Reservation> reservations = new ArrayList<>();
    @ManyToOne
    private VoleGenirique voleGenirique;
    @ManyToOne
    private CompagniesAerienne compagniesAerienne;

    public Vole(LocalDateTime date_departure, LocalDateTime date_arrive) {
        this.date_departure = date_departure;
        this.date_arrive = date_arrive;
    }
}