/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.app.entity.vole;

import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.Date;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "vole")
@Entity(name = "Vole")
@ToString
public class Vole {

    /*
    * ID Vole Sequence Generator (vole_sequence) with Strategy SEQUENCE
    * Column name is : vole_id
    * */

    @Id
    @SequenceGenerator(
            name = "vole_sequence",
            sequenceName = "vole_sequence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "vole_sequence"
    )
    @Column(
            name = "vole_id"
            ,nullable = false
    )
    private Long voleID;

    /*
     * Date of Starting Vole.
     * Type : LocaleDateTime
     * Column : vole_date_depart, Def (TIMESTAMP WITHOUT TIME ZONE) and nonnull
     * */

    @Column(
            name = "vole_date_depart",
            nullable = false
    )
    @JsonFormat(pattern = "yyyy/MM/dd")
    private Date date_departure;

    /*
     * Date of Ending Vole.
     * Type : LocaleDateTime
     * Column : vole_date_arrive, Def (TIMESTAMP WITHOUT TIME ZONE) and nonnull
     * */

    @Column(
            name = "vole_date_arrive",
            nullable = false
    )
    @JsonFormat(pattern = "yyyy/MM/dd")
    private Date  date_arrive;

    /*
     * Date of Margin between starting date of vole end ending.
     * Type : LocaleDateTime
     * Column : vole_interval
     * */

    @Column(
            name = "vole_interval"
    )
    private LocalDateTime interval;


    /*
    * Mapping RelationShip with Table : reservations, voleGenirique and compagniesAerienne
    *
    * */

//    @OneToMany(
//            mappedBy = "vole",
//            cascade = {CascadeType.ALL}
//    )
//    private Collection<Reservation> reservations = new ArrayList<>();
    @ManyToOne
    private VoleGenirique voleGenirique;
    @ManyToOne
    private CompagniesAerienne compagniesAerienne;

    public Vole(Date date_departure, Date date_arrive) {
        this.date_departure = date_departure;
        this.date_arrive = date_arrive;
    }
}