/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.tp.entity;

import lombok.*;

import jakarta.persistence.*;
import java.util.Collection;


@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table
public class Client {
    @Id
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "sequence_client"
    )
    private long id_client;
    private String nom;
    private String prenom;
    private String adresse;
    private String telephone;
    private String email;
    //ERD party
    @OneToMany(
//            cascade = {CascadeType.PERSIST,CascadeType.REMOVE},
            mappedBy = "client",
            fetch = FetchType.LAZY
    )
//    @JoinColumn(
//            name = "client_id",
//            foreignKey =
//            @ForeignKey("client_id_fk")
//
//    )
    private Collection<Reservation> reservation ;
}