/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.tp.entity;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import jakarta.persistence.*;
import java.util.Collection;

@Getter
@Setter
@NoArgsConstructor @AllArgsConstructor
@Table
@Entity

public class CompagniesAerienne {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id_compagnie;
    private String nomCompagnie;

    //ER Party
    @OneToMany(mappedBy = "compagniesAerienne",fetch = FetchType.LAZY)
    private Collection<Vole> vole;

    //à triter
    @OneToOne(mappedBy = "compagniesAerienne",fetch = FetchType.EAGER)
    private VoleGenirique voleCompanie = new VoleGenirique();

}