/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.tp.entity;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import jakarta.persistence.*;
import java.time.LocalDateTime;


@Getter
@Setter
@NoArgsConstructor @AllArgsConstructor
@Table
@Entity
public class Info_Escale {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id_escale;
    private LocalDateTime heur_arriver;
    private LocalDateTime heur_depart;
    @Transient
    private int duree;

    //ER party
    @ManyToOne
private Aeroport aeroport_escale;
    @ManyToOne
private VoleGenirique vole_escale;

}