/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.tp.entity;

import jakarta.persistence.*;
import lombok.*;

import java.util.List;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity(name = "Passager")
@Table(name = "passager")
@ToString
public class Passager {

    @Id
    @SequenceGenerator(
            name = "passager_squence",
            sequenceName = "passager_squence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "passager_squence"
    )
    @Column(
            name = "passager_id",
            nullable = false,
            insertable = false,
            updatable = false
    )
    private Long id;

    @Column(
            name = "passager_first_name",
            nullable = false,
            length = 25
    )
    private String first_name;

    @Column(
            name = "passager_last_name",
            nullable = false,
            length = 25
    )
    private String last_name;
    //ERD party
    @OneToMany(
            cascade = {CascadeType.PERSIST,CascadeType.REMOVE},
            mappedBy = "passager",
            fetch = FetchType.LAZY)
    private List<Reservation> reservation ;
}