/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.tp.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table
public class Passager {

    @Id
    @SequenceGenerator(
            name = "passagersquence",
            sequenceName = "passagersquence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "passagersquence"
    )
    private Long id_passager;

    @Column(
            name = "passager_first_name",
            nullable = false
    )
    private String first_name;

    @Column(
            name = "passager_last_name",
            nullable = false
    )
    private String last_name;
    //ERD party
    @OneToMany(mappedBy = "passager",fetch = FetchType.LAZY)
    private List<Reservation> reservation ;
}