/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.tp.entity;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import jakarta.persistence.*;
import java.sql.Time;
import java.util.*;

@Getter
@Setter
@NoArgsConstructor @AllArgsConstructor
@Table
@Entity
public class Vole {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long num_vole;
    private Date dateDépart;
    private Date dateArriver;
    private Time duré;

    //ER Party
    @OneToMany(mappedBy = "vole",fetch = FetchType.LAZY)
    private Collection<Reservation> reservation;
    @ManyToOne
    private VoleGenirique voleGenirique;
    @ManyToOne
    private CompagniesAerienne compagniesAerienne;

}